apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# configurations:
#   - k-config.yaml  
resources:
  - backendmodules.ui.crd.yaml
  - backendmodule.yaml
  - kubernetes-dashboard-admin.yaml
bases:
  - backend
  - web
