apiVersion: apps/v1
kind: Deployment
metadata:
  name: console-web
  labels:
    app: console
    kyma-project.io/component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: console
      # not used anymore but need to stay as the selector is immutable 
      kyma-alerts: enabled
      kyma-component: ui
      kyma-grafana: enabled
  template:
    metadata:
      labels:
        app: console
        kyma-project.io/component: frontend
        # not used anymore but need to stay as it is used in the selector
        kyma-alerts: enabled
        kyma-component: ui
        kyma-grafana: enabled
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: console
          image: "wawrzyn321/core"
          imagePullPolicy: IfNotPresent
          resources: {}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 6080
            initialDelaySeconds: 10
          ports:
            - containerPort: 6080
            - containerPort: 8080
          volumeMounts:
          - name: config
            mountPath: /usr/share/nginx/html/assets/config
        - name: core-ui
          image: "eu.gcr.io/kyma-project/core-ui:491eab72"
          imagePullPolicy: IfNotPresent
          resources: {}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 6081
            initialDelaySeconds: 10
          ports:
            - containerPort: 6081
            - containerPort: 80
          volumeMounts:
            - name: config
              mountPath: /var/public/config
      volumes:
      - name: config
        configMap:
          name: console-config
          items:
          - key: config.js
            path: config.js
