apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: web
resources:
  - configmap.yaml
  - deployment.yaml
  - service-core-ui.yaml
  - service-core.yaml
  - ingress-core.yaml
